client_config_backend: file
client_config:
    client_id: 161822541284-3vpv8kqhqvantc12are8pkbcqa2duup0.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive